client:
    key: ${TOSS_CLIENT_KEY}
cloud:
    aws:
        credentials:
            access-key: ${S3_ACCESS_KEY}
            secret-key: ${S3_SECRET_KEY}
        region:
            static: ap-northeast-2
        s3:
            bucket: ${S3_BUCKET_NAME}
jwt:
    access:
        expiry-millis: 3600000
    refresh:
        expiry-millis: 40000000
    secret: ${JWT_SECRET_KEY}
logging:
    level:
        com:
            fasterxml:
                jackson:
                    databind: DEBUG
        org:
            springframework:
                web: DEBUG
secret:
    key: ${TOSS_SECRET_KEY}
spring:
    application:
        name: ReVibe
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: ${SPRING_DATASOURCE_PASSWORD}
        url: ${SPRING_DATASOURCE_URL}
        username: ${SPRING_DATASOURCE_USERNAME}
    jpa:
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
        properties:
            hibernate:
                default_batch_fetch_size: 100
                enable_lazy_load_no_trans: true
                format_sql: true
        show-sql: true
    servlet:
        multipart:
            enabled: true
            max-file-Size: 5MB
            max-request-Size: 5MB