name: docker multi-stage build

# 워크플로우 실행 조건
on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - featureGitAction-cicd-구현

# 워크플로우 작업 정의
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3


      - name: Build and push
        uses: docker/build-push-action@v6
        with:
         file: ./Dockerfile
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_TAG_NAME}}:latest